### PR TITLE
Allow checked_arithmetic to be configured as default

### PR DESCRIPTION
**Pull request by philipp2100**
Solves #106.

### CODE REVIEW

**Comment by philipp2100** [comment]
Ok, that should be it. Sorry for the many followups -- I'm not good at macros...
Please squash.

**Comment by philipp2100** [comment]
Actually, there still might be an issue with the CMakeLists.txt: I'm not sure if it will set TYPE_SAFE_ARITHMETIC_UB to the default value, overriding TYPE_SAFE_ARITHMETIC_CHECKED even if that one is set...

**Comment by foonathan** [comment]
Sorry for the delay!

I reviewed your PR, but github seems to have lost the review, which I only noticed now...

To save time, I have implemented the changes I wanted myself. Thanks anyway.

**Comment by philipp2100** [comment]
Fine with me, thank you too!

**Pull request closed without merging**
