### PR TITLE
Add `hashable` base for `std::hash` of strong typedefs

### LINKED ISSUE #73: Enabled `std::hash` for `strong_typedef`s with `strong_typedef_op::hashable`
Greetings.

I just found myself specializing `std::hash` for some strong typedefs of mine which are provided for convenience. I thought it'd be great if the library provided a `strong_typedef_op` that enabled it.

I am available to write it. Would the name in the title be ok? How about copying the hash tests of other library components?

### PR DESCRIPTION
**Pull request by johelegp**
Resolves #73.
Do you think the documentation is clear enough? Should I maybe add an example?

### CODE REVIEW

**Comment by foonathan** [comment]
Is there any hash specialization written for a strong typedefs in this library? If so you can use hashable there and point the users to it.

**Comment by johelegp** [comment]
There isn't. Should I add one to the examples?

**Comment by foonathan** [comment]
Yeah, then just add one to the example.

**Comment by johelegp** [comment]
How does it look?

**Comment by foonathan** [comment]
Looks good, thanks.

**Pull request merged**
