### PR TITLE
Improvement of the dereference module

### PR DESCRIPTION
**Pull request by QuentinDuval**
Hi,

I was reading your awesome blog (https://foonathan.github.io/blog/2016/10/19/strong-typedefs.html) and then had a look at the strong_typedef on your GitHub. I had the need for this from almost a year now, and this helps a lot.

I also understood that you looked for a way to call arbitrary method from the underlying object of the strong_typedef. I saw the opportunity to provide the feature you desired by playing a bit with the dereference module you already provide. And I was considering tweaking your implementation like this for my need as well.

The rationale is that if a user makes use of the dereference on a strong_typedef wrapping a pointer, the semantic should not change. But then you can provide it when the user wraps a value type, and by the overloading of the "deref_impl" you can forward functions on the value as well.

I would be glad knowing what you think about it. My feeling is that it maybe a bad idea to mix it with the dereference operator.

Thank you,
Quentin

### CODE REVIEW

**Comment by foonathan** [comment]
This looks interesting but I don't really see a use. Do you have a concrete example where it might be useful?

**Comment by QuentinDuval** [comment]
Thank you for you answer!

Regarding the use case, I had a look at the dereference "module".
I figured that it allowed to use the wrapped type as you would use a wrapped type in a smart iterator.
But it seems to only work for pointer.

In my case, I wanted to avoid the pointer, mainly because:
- It makes aliasing very easy and can thus "break" the protection and encapsulation provided by the strong_typedef.
- I would prefer to stick to a value semantic (for example an family_name class that wraps a std::string)

At the same time, the dereference operator was really nice.
I figured that what I wanted is "similar" to the dereference operator of an std::optional.
And that there was nothing stopping the type_safe library to offer it.

As an example:

struct family_name
  : strong_typedef<family_name, std::string>
  , strong_typedef_op::dereference<family_name, std::string>
{
  using strong_typedef::strong_typedef;
};

Which would allow me to have the strong typing, plus the possibility to apply generic algorithms on it:

family_name f("Doe")
std::transform(f->begin(), f->end(), f->begin(), ::toupper);

**Comment by foonathan** [comment]
Ah, so you basically want operator. overloaded?

**Comment by QuentinDuval** [comment]
Yes, this is indeed a simpler way to formulate my use case.

**Comment by foonathan** [comment]
Sorry, I forgot about that PR :)

I'm not a huge fan of it: operator. would be a preferable syntax but it is not available. Also consider a member function of the typedef'ed type that returns the type itself - simply forwarding it would "break" the strong typedef.

So I won't merge your PR, if one really needs that, it's not hard to do.

**Comment by QuentinDuval** [comment]
No worries, I almost forgot it as well :)
And thank you for the time you took for answering the PR.

I agree with you about the "operator.".

I think the argument about the reference to itself is valid too. But I would point out it is already the case that the strong typedef is "broken" when we use the dereference operation. The same kind of argument can be used: the function called can also return a reference to the object itself.

In any case, I will keep following the progress on your type_safe library :)

**Pull request closed without merging**
