### PR TITLE
Provide support for explicit operator bool

### PR DESCRIPTION
**Pull request by kyku**

### CODE REVIEW

**Comment by foonathan** [comment]
Could you test it with a type that doesn't have a constexpr operator? I think it might be an issue.

**Comment by kyku** [comment]
Thanks for pointing that out. Using a static_cast<bool>(...) seems to solve this problem (tested on GCC 7.3.1 and clang 6.0.0). And so is removing the constexpr. Is that acceptable?

**Comment by foonathan** [comment]
Just to clarify: your code still has constexpr? If it works, I'm fine with leaving at is.

**Comment by kyku** [comment]
Yes, the updated PR still contains constexpr in explicit operator bool().

**Comment by foonathan** [comment]
Good, I wasn't sure the PR was updated properly, I remembered issues with constexpr on the strong typedef member functions and was surprised it works.

**Pull request merged**
