### PR TITLE
Write an architecture independent cmake version file

### PR DESCRIPTION
**Pull request by jeromehue**
#136

### CODE REVIEW

**Comment by foonathan** [comment]
Can you also update the vendored copy of `debug_assert` now? Just copy the CMakeLists.txt over.

**Comment by jeromehue** [comment]
I am not sure to understand, havn't you already merged it ? https://github.com/foonathan/debug_assert/pull/20

**Comment by foonathan** [comment]
> I am not sure to understand, haven't you already merged it ? [foonathan/debug_assert#20](https://github.com/foonathan/debug_assert/pull/20)

Yes, I've merged it. However,  because it's just two files and issues in the past, type_safe also has its own copy of the library here: https://github.com/foonathan/type_safe/tree/main/external/debug_assert

Changes in the repository don't affect this copy.

**Comment by foonathan** [comment]
Thank you!

**Pull request merged**
