### PR TITLE
Fix `get<StrongTypedef>` for rvalues

### PR DESCRIPTION
**Pull request by johelegp**

### CODE REVIEW

**Comment by foonathan** [comment]
Fyi: Master is currently failing anyway.

**Comment by johelegp** [comment]
Yeah. I noticed the errors mention something about an `optional`. The local tests are passing, though.

**Comment by foonathan** [comment]
Could you rebase your branch on top of master?
I've protected master now and can't merge the PR otherwise.

**Comment by johelegp** [comment]
Should I keep the rvalue support commit? Many more operators could benefit, but using [taocpp/operators](https://github.com/taocpp/operators) would be simpler.

**Comment by foonathan** [comment]
I'm interested in rvalue support, you can use the operators library if that works better.

**Comment by johelegp** [comment]
I ended up adding the support without the operators library. I don't think there are other operators that could benefit.
For the `constexpr` mixed operators, I cast `other` to `type` to be consistent with the non-`constexpr` mixed operator.
As a follow up, rvalue support for `other` could be added. But that's not as trivial as forwarding, because there's a conversion to `type`.

**Comment by foonathan** [comment]
The new operators don't allow implicit conversions anymore, which breaks the tests.

It should be fixed by manually overloading for all lvalue/rvalue combinations (i.e. two overloads for the $= versions, four for the $ versions).

**Comment by johelegp** [comment]
Indeed, I accidentally overconstrained the operators. I have manually overloaded for all lvalue/rvalue combinations.

The first error remains the same. Have I done something wrong?

**Pull request merged**
